# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 500bb22b8827a74672bb5f77ed7895ce88e43811101fb605b42550842eecba2ae08cc5bd8197aa37776a5a524965899f316021760476fde2bfa8b6f2934c1d71

test:
  secret_key_base: 7615e8feb15d91eeb973a7c692238150d713ec7c2cf26333fa38ac35c77b0fbaa208d6190189650d4f6a92c624b47547598955dced8711c82786561f26ad766e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
